
require('base')
require('highlights')
require('maps')
require('plugins')

require('config.bufferline')
require('config.dashboard')
require('config.lualine')
require('config.neosoloarized')
require('config.nvim-tree')
require('config.telescope')
require('config.comment')
require('config.toggleterm')
-- LSP
require('config.lspconfig')
require('config.treesitter')

require('config.cmp')
require('config.null-ls')
require('config.lspkind')
require('config.autopairs')
require('config.luasnip')
require('config.luasaga')
require('config.ts-autotags')
